services:
  api:
    build:
      context: .
      dockerfile: ctp-api/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ctp-api/.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
      - ctp-api/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
