package models

type SlotGenerationMode int

const (
	SlotGenerationModeRandom              SlotGenerationMode = iota
	SlotGenerationModeMaximizeAirportPairs
	SlotGenerationModeMaximizeSlots
)

type DepartureTimeWindowOffsetsCalculationMode int

const (
	DepartureTimeWindowOffsetsCalculationModeNone DepartureTimeWindowOffsetsCalculationMode = iota
	DepartureTimeWindowOffsetsCalculationModeEarliestRoutes
	DepartureTimeWindowOffsetsCalculationModeLatestRoutes
	DepartureTimeWindowOffsetsCalculationModeRouteAverage
)

type WaypointThroughputCalculationMode int

const (
	WaypointThroughputCalculationModeNone WaypointThroughputCalculationMode = iota
	WaypointThroughputCalculationModeFirstWaypointsOfNATRouteSegmentsOnly
	WaypointThroughputCalculationModeAllWaypoints
)
